name: Deploy MultiContainer
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t arun/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true arun/react-test npm test a -- --coverage

      - run: docker login -u ${{ secrets.DOCKER_USER_NAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t arun/multi-client-10-14 ./client
      - run: docker build -t arun/multi-nginx-10-14 ./nginx
      - run: docker build -t arun/multi-server-10-14 ./server
      - run: docker build -t arun/multi-worker-10-14 ./worker

      - run: docker push arun/multi-client-10-14
      - run: docker push arun/multi-nginx-10-14
      - run: docker push arun/multi-server-10-14
      - run: docker push arun/multi-worker-10-14

      - name: Generate Deployment Package
        run: zip -r deploy.zip . -x '*.git*'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'